apiVersion: v1
entries:
  llm-engine:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.943764293+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: fd86221c407e38e1dd9845597c6f0b710799ac6c1db59d733ca339b3f61e02f0
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.939660269+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: 27e368dd94333b560d1772fc8c4cf3dc89efa5c4fad87e4f00a0acd768f2a03e
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.935237419+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: 2f28241803073354a92063a0faaba234b3c344fb0b0bf5d2ce037bb8e7e89972
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.930985484+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: 93892c23477fb7f710b79f23bdb148132bb30e9f3ba86ecbae7a44535678ffc4
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.926052395+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: ca27d20f7ee49ce03a1cac62569ca8f437af09b885d1e7087e814eb97118be39
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.921073893+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: 28378345cf86c5a9696770e2a6df9121109f54a4f2ad80ccd078a5025c6ec06b
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-07T10:31:42.915581098+02:00"
    dependencies:
    - condition: kuberay-operator.enabled
      name: kuberay-operator
      repository: https://ray-project.github.io/kuberay-helm/
      version: 1.4.0
    description: A Helm chart for deploying LLM Engine with multiple models using
      Ray Serve
    digest: 6433b81f5777b766a488753e703b7a34ec97206b34c34375f0be3513111ad348
    name: llm-engine
    type: application
    urls:
    - https://kaasops.github.io/llm-engine/helm/packages/llm-engine-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-07T10:31:42.909613101+02:00"
